export enum MovieGenres {
  Action = 'Action',
  Animation = 'Animation',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Drama = 'Drama',
  Fantasy = 'Fantasy',
  Historical = 'Historical',
  Horror = 'Horror',
  Romance = 'Romance',
  ScienceFiction = 'Science-fiction',
  Thriller = 'Thriller',
  Western = 'Western',
  Other = 'Other',
}
